### ISSUE TITLE
Kergliiklustee Hoiu tee 6 ja 10 vahel

### ISSUE THREAD

**Issue by tormi** [tormi/KOV#11]
Kergliiklustee Hoiu tee 6 ja 10 vahel on hetkel valel pool teed, tuleks rajada ka teisele poole, et tõsta kergliiklejate liiklusohutust, kaart: [kaardid/11.geojson](https://github.com/tormi/KOV/blob/master/kaardid/11.geojson)

![hoiu 6 - 10 klt](https://cloud.githubusercontent.com/assets/146800/8571699/fa8d919e-2590-11e5-9344-092aa3463d81.png)

Valla 08.07.2015 tagasiside - ehitusprojekt on peaaegu valmis, maa omandamise (Hoiu 6) kokkulepped olemas: 
_Püüdsime maksimeerida jalakäijate ja ratturite ohutust. Kõnniteed on planeeritud mõlemale poole Vae ja Hoiu tn (Graderi suuline nõusolek on olemas, kirjalikku notariaalset eelkokkulepet valmistame ette), lisaks puuduv kõnniteejupp Vae tn ääres. Hoiu-Vae-Kuuse põik ristmik lahutatakse kaheks eraldi ristmikuks, et oleks ohutum. Kahte kohta on kavandatud jalakäijate istumisalad koos linnamööbli ja haljastusega._

**Comment by tormi** [comment]
@wipsise, vald lubas projekti sel nädalal tagasiside andmiseks saata.

**Comment by tormi** [comment]
Asendiplaanid saabusid:
- Vae tn, [Hoiu_Vae_asendiplaan_liiklusskeem_1.pdf](https://github.com/tormi/KOV/blob/master/materjalid/Hoiu_Vae_asendiplaan_liiklusskeem_1.pdf)
- Hoiu tn, [Hoiu_Vae_asendiplaan_liiklusskeem_2.pdf](https://github.com/tormi/KOV/blob/master/materjalid/Hoiu_Vae_asendiplaan_liiklusskeem_2.pdf)

**Comment by tormi** [comment]
Hoiu-Vae ristmik on lahendatud 2-osalisena, mis on ilmselt hea lahendus kuna tagab, et kergliikleja marsruudid järgivad praeguseid väljakujunenud radu (punane katkendjoon):
![hoiu_vae_ristmik_aerofoto](https://cloud.githubusercontent.com/assets/146800/8591732/f8583d14-2632-11e5-82a0-4ae9556bd9ef.PNG)
![hoiu_vae_ristmik](https://cloud.githubusercontent.com/assets/146800/8591652/76ded75c-2632-11e5-90b7-db46cc45525c.PNG)

**Comment by tormi** [comment]
_Kahte kohta on kavandatud jalakäijate istumisalad koos linnamööbli ja haljastusega_:
![hoiu_vae_ristmik_puhkekohad](https://cloud.githubusercontent.com/assets/146800/8591944/506c7410-2634-11e5-9a19-2c9aa3c74ca1.PNG)
Teen ettepaneku kas üks neist tõsta ümber või lisada kolmas puhkekoht Hoiu tn veehoidla juurde, mis on puhkekohana trassi kõige atraktiivseim paik:
![hoiu_veehoidla](https://cloud.githubusercontent.com/assets/146800/8591994/b260b7c6-2634-11e5-9a0a-0b5060d39ee8.png)
Hetkel ei ole sinna puhkekohta projekteeritud:
![hoiu_veehoidla_projekt](https://cloud.githubusercontent.com/assets/146800/8592062/1cb74482-2635-11e5-95a0-603e5ab78a6c.png)

**Comment by tormi** [comment]
Lisaks, kuidas on eelmisel joonisel lahendatud jalakäijate juurdepääs Hoiu tn 7 ja 9-le? Projektis on olemasolev kitsas kergtee sebrast kurvini asendatud muru (heleroheline) ja peenraga (pruun).

**Comment by tormi** [comment]
_lisaks puuduv kõnniteejupp Vae tn ääres_ - äge!
![vae_klt](https://cloud.githubusercontent.com/assets/146800/8592313/fc1ef88a-2636-11e5-9e6c-0698a7e08788.PNG)
![vae2_klt](https://cloud.githubusercontent.com/assets/146800/8592337/2af5e1be-2637-11e5-92d5-cf02f7186001.PNG)

**Comment by wipsise** [comment]
ei õnnestu neid pdf kätte saada.

raul

ps. kas tead, kas Jõekääru pargi uuele sillale on ka projekt tellitud, mis
ehitushankesse läks?
1. juuli 2015 12.56 kirjutas Tormi Tabor notifications@github.com:

**Comment by tormi** [comment]
Ma parandasin viited ära pärast kande tegemist, aga Github ilmselt saatis teavituskirja katkiste URL'iega. Proovi siit: https://github.com/tormi/KOV/issues/11#issuecomment-119879868

> ps. kas tead, kas Jõekääru pargi uuele sillale on ka projekt tellitud, mis ehitushankesse läks?

Hankedokumendid on siin (sh sillaprojekt dwg-s): https://riigihanked.riik.ee/register/hange/164864

**Comment by wipsise** [comment]
ok, nüüd sain lahti. kas kommentaaridega kannatab oodata järgmise nädalani?
siin on mitu asja kohe päris valesti, aga mul pole aega praegu joonistada.

Raul
1. juuli 2015 19.45 kirjutas Tormi Tabor notifications@github.com:

**Comment by tormi** [comment]
Ma arvan, et järgmine nädal on veel ok.

**Comment by tormi** [comment]
Projekt valla ftp-s: ftp://ns.sauevald.ee/Hoiu%20ja%20Vae%20tn/

**Comment by wipsise** [comment]
Hoips

Turismireis Eestisse kujunes intensiivseks, ei saanud mahti varem. Minu
arvates on see ringristmiku koht. Kui ringi ei tehta, siis ristmiku
geomeetria tuleb ikka korda teha. Liiklusvood hakkavad siin teistpidi
käima, kui Laagri ümbersõit lõpuni ehitatakse.

Parimat

Raul@Schipol

2015-07-13 13:49 GMT+04:00 Tormi Tabor notifications@github.com:

**Comment by tormi** [comment]
[Rauli märkused](https://github.com/tormi/KOV/raw/master/materjalid/Hoiu_Vae_asendiplaan_liiklusskeem_1_RV.pdf) (pdf)

**Comment by tormi** [comment]
Projekti võiks laiendada Vae tn 2 esise kergteega (#16)

**Comment by tormi** [comment]
22 juuli 2015 22.01 kirjutas Kalle Pungas Kalle.Pungas@sauevald.ee:

Mul miskipärast ei õnnestu seda faili kätte saada.

Ringristmikku pole sinna otstarbekas teha, kuna see võiks soosida Hoiu ja Vae tn transiitliiklust Kuuse põik-Redise suunale või veel hullem, Kuuse põik-Kuuse suunale. Kõige ohutum on nii, et las autod sõidavad mööda Hoiu-Vae magistraaltänavat ja jõuavad läbi vallamaja ees oleva ringristmiku Veskitammi tänavale (ja Möldre teele). Kuuse põik, Redise ja Kuuse tn aga jäägu kvartalisisesteks rahulikumateks tänavateks, nii on kõige ohutum ja elanikele keskkonnamõju kõige väiksem.

Kalle

9 juuli 2015 20.49 kirjutas Kalle Pungas Kalle.Pungas@sauevald.ee:
1. Meil oli samuti soov panna kolmas puhkekoht veehoidla juurde. Aga kuna taotleme raha raudteepeatuste meetmest ja seal on oluliseks hindamiskriteeriumiks maa omamine (kaks puhkekohta on projekteeritud valla maale), siis ajafaktorit arvestades (taotluste esitamise tähtaeg on 10. august) me ei julgenud riskida punktide kaotamisega ning jätsime selle praegu suurest teeprojektist välja. Puhkekoha maksumus on võrreldes tee-ehitusega marginaalne ja mõistlikum on see teha edaspidi kas valla raha eest või kui saame toetuse ja jõuame maa omandada, siis ehk õnnestub see ehituse käigus sokutada tellija reservi hulka. See meede on nimelt Eestis esimene inframeede, kus on lausa soositud jalakäijate ja kergliiklejate jaoks vajalikud avaliku ruumi rajatised.
2. Meil oli projekteerijale samuti ettepanek säilitada olemasolev kitsas kõnnitee ja suuliselt oli ta sellega nõus. Pean nüüd küsima, kas ta lihtsalt unustas meie ettepaneku sisse viia või tekkis mingi oluline põhjendus, miks ta seda ei teinud. Loodan, et õnnestub see alles jätta, kuna äsjase ÜVK projekti käigus sai see uue katte ja äralõhkumise põhjuseks ei saa enam olla ka vana lagunenud asfalt. Uurin seda teemat.
   
   Kalle
   
   From: Tormi Tabor tormi.tabor@gmail.com
   Sent: 09 July 2015 12:41
   To: Kalle Pungas
   Subject: Re: FW: Hoi Vae projekt
   
   Tere,
   
   Saadan esmase tagasiside.
   
   Üldjoontes kiiduväärt lahendus! Minu märkused:
   1. Tõsta üks kavandatuist ümber või lisada kolmas puhkekoht Hoiu tn veehoidla juurde, mis on puhkekohana trassi kõige atraktiivseim paik: https://github.com/tormi/KOV/issues/11#issuecomment-119884213
   2. Kuidas on eelmisel joonisel lahendatud jalakäijate juurdepääs Hoiu tn 7 ja 9-le? Projektis on olemasolev kitsas kergtee sebrast kurvini asendatud muru (heleroheline) ja peenraga (pruun). https://github.com/tormi/KOV/issues/11#issuecomment-119889259
   
   Tervitades,
   Tormi

**Comment by tormi** [comment]
Saatsin Rauli ettepanekud vallale uuesti eraldi failina.

**Comment by wipsise** [comment]
Ringristmik ei suurenda kuidagi transiiti, pigem vastupidi. Eriti raskeveokitele on ringid pigem tülinaks. Projekteeritud skeem ka kuidagi liiklemist ju ei takista!?
Transiiti soodustaks Veskitammi - Pärnu maantee ristmikul vasakpöörete võimaldamine, mida tuleks kindlasti vältida.
Kas see on nüüd ametlik arutelufoorum?

**Comment by tormi** [comment]
@wipsise, saabus valla tagasiside.

> 23 juuli 2015 22.22 kirjutas Kalle Pungas Kalle.Pungas@sauevald.ee:
> 1. Ringristmiku osas juba kommenteerisin, et me ei soovi suunata transiitliiklust elurajoonidesse. Sama põhjus on ka peatee senise suuna säilitamisel. Sellise liiklusskeemi korral on kõrvalteede liikluskoormus võrreldes peateega oluliselt väiksem, mistõttu pole ka karta ummistusi. 
> 2. Kuuse põik raadiused on meelega suuremad, kuna valla ja küttefirma koostöös on kavandamisel hakkepuidu katlamaja ning arvestasime pikkade veokitega.
> 3. Kuuse põik geomeetria osas võib teha nii või naa. Mina pigem toetan kergtee jaoks väikest jõnksu, kuna igaks juhuks on ristmikul mõistlik ratturite kiirus väikese kurviga maha võtta. Liiklusseaduse järgi ju peab rattur ületama sõidutee jalakäija kiirusega (prg 31 lg 9).
> 4. Vae tn-l oleks hea tahtmise korral osaliselt võimalik kergtee ja sõidutee vahele teha betoonkivist riba (nagu Hoiu tn-l). Samas on siin üpris oluline küsimus ratturite ohutus. Laskuval suunal võib kiirus taganttuule toel küllalt suureks minna, aga Sagro hoovist väljasõit on just täpselt mäe all. See on väga riskantne ja ohtlik koht, kuna nähtavus sisuliselt puudub. Panime sinna kergteele küll täristijooned ja spets liiklusmärgi, aga passiivse kiiruseohjeldajana on äärekiviga kergtee päris hea variant. Raudteeülekäikude juures kasutatavad torupiirded oleksid minu arust siin palju nõmedamad ja ratturitele ohtlikumad (pimedal ajal ei pruugita märgata). Nii et ma pigem eelistaksin siin mõistlikku ohutust mugavusele.
> 
> Kalle

Raul:

> Kas see on nüüd ametlik arutelufoorum?

Ei ole, siin hoian enda teemade üle järge, mis FB-s ja kirjavahetustes kipub kaduma. Feel free vallaga otse suhtlema, aga hea oleks, kui mind infoväljas hoiaksid.

**Comment by wipsise** [comment]
1. milisest transiitliiklusest on jutt? ja kuidas ringristmik seda elamurajoonidesse suunab, jääb arusaamatuks.
2. pikad veokid saavad hakkama ka väiksemate raadiustega. kui ma saan cad faili, siis võin demonstreerida. suuremad raadiused ainult suurendavad sõiduautode kiirusi ja suuremad kiirused soodustavad läbivat liiklust. järgmisena hakatakse siis jälle pooletoobiseid künniseid teele panema, et planeerimisviga "parandada".
3. kuidas sellel pildil olev jõnks jalgrattureid rahustab? puhas jaburdus. ohutuse jaoks on vaja nähtavust. 

![2015-07-09-instituudi-jalgtee](https://cloud.githubusercontent.com/assets/11847573/8871739/a175ec30-3208-11e5-84b2-374f0f9a734e.jpg)

Seadus ei taga ohutust. Märgid ja paragrahvid on vajalikud vaid süüdlase määramiseks.
1. Ohutuse tagab eraldatus. Eraldusribale mahuvad märgid, mis ei tohi olla jalakäija/ratturi liikumisruumis. Hoovist väljasõites jällegi tuleb tagada nähtavus. Teiseks tuleb anda jalgratturile prioriteet - jalgrattatee peab olema jätkuv ja mahasõidul tõstetud, mitte mahaviidud äärekividega. Lisaks muidugi väljasõitjatele märgid Anna teed ja Ristuv rattatee.

Jah, ohutus eelkõige. Ja mugavus jalgratturile, mitte autole. Jalgrattureid ei ole reeglina vaja rahustada, kuigi seda Eestis aktiivselt nonde samade torupiiretega tehakse. Ka Saue vallas.

http://wipsise.blogspot.com/2014/07/aitab-ohtlikust-torupornost.html

Kas valla kodukale ei saaks normaalset arutelufoorumit lisada? Näoraamat selleks ei sobi on tõepoolest saast ja sealt ei leia midagi üles. sauekas.ee lehel on ka foorum, seda ei ole üles leitud.

**Comment by wipsise** [comment]
ps, ma nüüd vaatasin seda Tiltsi tehtud Jõekääru silla projekti ka. Ei ütle vormistuse kohta midagi, Nadja teeb hoolsat tööd. Aga no krt, kas Saue vallas tõesti ei või silda teha kaldast kaldani, et peab sängi kitsendama? Ei ole kallasrada. Massiivsed sambad, mida ehitati ehk üle-eelmisel sajandil. Kurb. Ja kallis. Ja siis see piirete disain, kuku pikali! Tõsiselt, need terasraamid ei ole isegi mitte tuulekindlad. Millistele koormustele need rehkendatud on?
Mis on aastane hoolduseelarve? 
Kes arhitekt on?

Arusaamatu on ka see, kuhu ja kuidas see tee ühendub. Siit tekivad jälle uued konfliktid, mida keegi ei ole osanud näha. Näiteks võib üsna kindel olla, et Veskitammi tänavat pidi liikuvad lapsed hakkavad nüüd teed ületama enne silda. Torupiirded ja tarad valmis panna!
Kooskõlastuste tabel on tühi, kas Maanteeamet on kooskõlastanud?

**Comment by tormi** [comment]
![hoiu_6_araloige](https://cloud.githubusercontent.com/assets/146800/10691815/e10c43a2-7994-11e5-8e63-182a8436645a.PNG)
[Korraldus nr 787_Hoiu_tn_6_äralõige.pdf](https://github.com/tormi/KOV/files/19313/Korraldus.nr.787_Hoiu_tn_6_araloige.pdf)
Allikas: http://server.amphora.ee/atp/sauevald/index.aspx?type=12&id=235305

**Comment by wipsise** [comment]
Tore, aga kuidas saab tasuta võõrandada? Ühe euro eest saaks aru, aga
tasuta saab omandada, mitte võõrandada. Korraldusest puuduvad ka
konkreetsed viited valla ja maaomaniku vahelisele kokkuleppele,
läbipaistvuse huvides peaks olema selge, mida kokkulepe veel sisaldab.
Lihtsalt sellised tähelepanekud.

Parimat,
Raul
1. oktoober 2015 15.47 kirjutas Tormi Tabor notifications@github.com:

**Comment by tormi** [comment]
[Garder Service Tootmine OÜ avaldus katastriüksuse Laagri alevik Hoiu 6 jagamiseks](http://server.amphora.ee/atp/sauevald/index.aspx?type=16&id=236423)
![grader_avaldus](https://cloud.githubusercontent.com/assets/146800/10904183/baf65378-8219-11e5-8e54-a31bc39b35af.PNG)
